### ISSUE TITLE
running seems to be halted but no errors.

### ISSUE THREAD

**Issue by juancresc** [carringtonlab/TargetFinder#4]
I'm running targetfinder with a very small sequence (DEseqs.1.fa, a 1000  bp sequence ). It seems to be running forever (20 minutes and waiting)

`./targetfinder.pl -s GGAAGAGGAUCGUUUAACUGUAGCAAGA -q Cluster_24 -d ../../data/DEseqs.1.fa
`

```
$ tail -f targetfinder.log
Small RNA = GGAAGAGGAUCGUUUAACUGUAGCAAGA
Query name = Cluster_24
Creating temporary file /var/folders/qg/k59zg13n4y3f7ldwj1j91j9m0000gn/T/R3wtcPhrBR
 Running /Users/juan/Documents/manu/dev/vms/bio/bio/MRCV/scripts/TargetFinder/fasta-35.4.12/bin/ssearch35_t... Running /Users/juan/Documents/manu/dev/vms/bio/bio/MRCV/scripts/TargetFinder/fasta-35.4.12/bin/ssearch35_t...
```

**Comment by nfahlgren** [comment]
It's not what I would call fast but usually runs in a minute or less typically. Could you copy your example database sequence here and I can test it on my end.

**Comment by juancresc** [comment]
Yes:


>TRIAE_CS42_U_TGACv1_642573_AA2119860.2 cdna
scaffold:TGACv1:TGACv1_scaffold_642573_U:68956:76632:1
gene:TRIAE_CS42_U_TGACv1_642573_AA2119860 gene_biotype:nontranslating_CDS
transcript_biotype:nontranslating_CDS
GTTATCCGTTTCTTGCTACTTGAAGAACAGGAGGGAGATGATGATGAACTCACTCTTCAA
CCAACTTTGCTATCATAAGGAAGGAAGCTCAAGCTGTCATCGATTTGGTTACTAAGGATG
CTATCCATGGGAGCGAAACTGGGAAAGCAATTTCGTTTTATGTTCTTGATTCATTAGTTA
GTATTGACCATGAAAAGTATTTCTTAAACCAGCTTCAAAGTCGAGGAATTCTCAGATCAT
GTCTAACTGATGTTAGCAACTATTTGTCAAAGGACATGTCATTCTCATCAGAGTTTTCAC
AGCGGTTTTGCACTATTGATGCTCAGTTTTCATTACTTCTGAGAATCACTCACCATTATG
GCAAACATGGCTCTCAGATTTTGTTATCCATGGGTGCTTTACAAAATCTTTCATCGTGCA
ACCTCTCGGGTTATCAGAAAAAGGGAAGTTCAAGGCTAAACTCCAATGTTGTGAAGGAAC
GAGCTGGGGAAATTGACAAGAAGTGGTCTCTTACTGCACCAGTACTGCGGATAATCACAT
CTTTCACATCCCTCGTGGACTCAGCTGATTTTCTTGAGGTGAAGAACAAAATTGTACGTG
AGATAGTGGATTTTGCCAAGCAGCATCAGTCCATTTTTAATAGCATTTTAAGAGAGAACA
TATCTGGAGCTAATGCCTTCAGCTTGGAGCGGCTTAATATGGTGGTTTCTATTCTCAGCA
AGATATGGGCATACGAGGAAAATGATGAATGCAGCTATGTCCAAGATCTATTCTCCATGA
TGCATTCTCTTTTTAGTCTTGATTTTGGATCTCTGAATTTCATTCAATCACCAAATATGA
TTGAGAATCAGAAGTCAGAGTTGGTATTATTTGGTATCTGCTTTGGCCTAATCTCTTACC
TATATTTTCTGGCTACAAAGAAGAACATGCGGTTTCAAGTTCGTGATTTGAATGAGTTAT
CTAGGAAGGAGGTCGATGAGATAATAAAAGTATGCATGAAGCAAGATTGCATCTCGCCCA
ATGATAACATCCGTAAAAGGAGATATATTGCAATGATAGATTTGTGTTGCATGGCTGGCA
ACCGAGACCAGCTTATAACACTTCTACTCCAAGTCGCCGAATGTGCCATCACTATTCTCC
TTGTTCATTTCCACGATGAAGCTTGTGCAGAAGACTTGTCTTCATTTTCCGATGAACTAC
TCCCTTTATTGGAGAGGCTAGAGCATCTAAAAGAGGACAAAGTTGGACGTAATCTCAAGT
TGTTCTACAGATCTGTTAGCACTCTGAAAGAGATGACCGTAAGAAGCATGACCATGTGAT
GGATATCGGGGAGCAGTATACAATAGAAATGATTTGTAGGATATGTGTAACAATGTTGTT
GTATATGGTGACTTGCTGGCATATCGAAATGTTATTGCTCTGGTGAGAGGCCAATTTCTG
CTTTGATATGTTGTTGATTGGGGAATTCAATAGTTTGGTCAAATTGTAAATTGATCTCCA
TCTTGACATTCATAATTTGGTGGATTTGTTGTTAAAGGTATGGACTATCCTTATTTTGGC
TGTTTACATGAAGGGAAACACCTCCCTACAGTAGTCTGATGTGAATCATTTGTCGGACTT
GTTGGAAAACGTCGGTTTGTATTTGATCTCATGGCTGAGAGAAGCCCTTAAATTAAGCCT
GATGTTTTTTGGGTTT





--
*Juan Manuel Crescente*

​
This message is confidential. It may also be privileged or otherwise
protected by work product immunity or other legal rules. If you have
received it by mistake, please let us know by e-mail reply and delete it
from your system; you may not copy this message or disclose its contents to
anyone. Please consider the environment before printing this email.

**Comment by nfahlgren** [comment]
When I run it it immediately returns `No results for Cluster_24`. The log has the following:

```
Small RNA = GGAAGAGGAUCGUUUAACUGUAGCAAGA
Query name = Cluster_24
Creating temporary file /tmp/E2b5F819MW
 Running ssearch35_t... Running ssearch35_t...
# ssearch35_t -n -H -Q -f -16 -r +15/-10 -g -10 -w 100 -W 25 -E 100000 -i -U -T 1 /tmp/E2b5F819MW test.fasta 1
SSEARCH searches a sequence data bank
 version 35.04 Feb. 20, 2010
Please cite:
 T. F. Smith and M. S. Waterman, (1981) J. Mol. Biol. 147:195-197;
 W.R. Pearson (1991) Genomics 11:635-650

Query: /tmp/E2b5F819MW
  1>>>Cluster_24 - 28 nt (reverse complement)
Library: test.fasta    1696 residues in     1 sequences

   1696 residues in     1 sequences
Statistics: (shuffled [500]) MLE statistics: Lambda= 0.0728;  K=   336
Algorithm: Smith-Waterman (PGopt) (6.0 Mar 2007)
Parameters: +15/-10 matrix (15:-10), open/ext: -16/-10
 Scan time:  0.230

The best scores are:                                                                              s-w bits E(1)
TRIAE_CS42_U_TGACv1_642573_AA2119860.2 cdna scaffold:TGACv1:TGACv1_scaffold_642573_U:6 (1696) [r]  250 17.9    0.18

>>TRIAE_CS42_U_TGACv1_642573_AA2119860.2 cdna scaffold:TGACv1:TGACv1_scaffold_642573_U:68956:766  (1696 nt)
rev-comp s-w opt: 250  Z-score: 58.1  bits: 17.9 E(): 0.18
Smith-Waterman score: 250; 60.0% identity (80.0% similar) in 30 nt overlap (1-28:1527-1556)

                                        10          20
Clust-                          UCUUGCUACAG-U-UAAACGAUCCUCUUCC
                                : :::.:: :: : :..:: :::::. :..
TRIAE_ CUUGACAUUCAUAAUUUGGUGGAUUUGUUGUUAAAGGUAUGGACUAUCCUUAUUUUGGCUGUUUACAUGAAGGGAAACAC
            1510      1520      1530      1540      1550      1560      1570      1580



28 residues in 1 query   sequences
1696 residues in 1 library sequences
 Tcomplib [35.04] (1 proc)
 start: Thu Jun 28 13:34:42 2018 done: Thu Jun 28 13:34:43 2018
 Total Scan time:  0.230 Total Display time:  0.000

Function used was SSEARCH [version 35.04 Feb. 20, 2010]
done
 Parsing results... Parse results...
     HIT ACCESSION = TRIAE_CS42_U_TGACv1_642573_AA2119860.2 cdna scaffold:TGACv1:TGACv1_scaffold_642573_U:68956:766
     miRNA = AGAACGAUGUC-A-AUUUGCUAGGAGAAGG
     TARGET = UGUUGUUAAAGGUAUGGACUAUCCUUAUUU
done
 Scoring alignments... Score alignments...
done
```

Not sure if you see anything in there that helps...

Is it possible it's not able to write the temporary files?

**Comment by juancresc** [comment]
Seems to be blocking in the ssearch. I'm using the same version. When listing processes it is like hanged in there. If I run the ssearch command separately I get a result instantly. 

This is happening in macOS

**Comment by nfahlgren** [comment]
Some ideas:

1. Does it work if you use ssearch instead of ssearch_t?
2. Is it possible that Perl in your setup is not allowed to execute shell commands?

**Comment by juancresc** [comment]
I've realized that if I run the ssearch command directly in the command
line, it never ends. So the issue is likely related to that, and not to
targetFinder itself.

This is the command:

 ssearch35 -n -H -Q -f -16 -r +15/-10 -g -10 -w 100 -W 25 -E 100000 -i -U
-T 1 /var/folders/qg/k59zg13n4y3f7ldwj1j91j9m0000gn/T/eQV_vhudjq
../data/head_rice.fa 1


I'll have to go that direction, thank you!

**Comment by juancresc** [comment]
Using an updated version of FASTA seems to be working. The only thing to modify is:

my $fasta = "ssearch36";
